package com.mycompany.twit;

public class InternalInteracciones extends javax.swing.JInternalFrame {

    public InternalInteracciones() {
        initComponents();
        UsuarioInfo usuarioActual = user_actual.getUsuarioActual();

        if (usuarioActual != null) {
            if (usuarioActual.isCuentaActiva()) {
                // Obtener el arreglo de menciones del usuario actual
                Twit[] menciones = usuarioActual.obtenerMenciones();

                // Limpiar el área de texto antes de mostrar nuevas menciones
                jTextAreaInteracciones.setText("");

                // Si no hay menciones, mostrar un mensaje
                if (menciones.length == 0) {
                    jTextAreaInteracciones.append("No tienes menciones.\n");
                } else {
                    // Mostrar las menciones en el área de texto
                    for (Twit mencion : menciones) {
                        if (mencion != null) {
                            jTextAreaInteracciones.append(mencion.toString() + "\n");
                        }
                    }
                }
            } else {
                // La cuenta está desactivada, no mostrar menciones
                jTextAreaInteracciones.setText("Tu cuenta está desactivada. No se muestran menciones.\n");
            }
        } else {
            jTextAreaInteracciones.setText("No hay un usuario logueado.\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInteracciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInteracciones = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(null);

        jLabelInteracciones.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabelInteracciones.setForeground(new java.awt.Color(0, 255, 255));
        jLabelInteracciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInteracciones.setText("Interacciones");

        jTextAreaInteracciones.setEditable(false);
        jTextAreaInteracciones.setBackground(new java.awt.Color(0, 0, 0));
        jTextAreaInteracciones.setColumns(20);
        jTextAreaInteracciones.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jTextAreaInteracciones.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaInteracciones.setLineWrap(true);
        jTextAreaInteracciones.setRows(5);
        jTextAreaInteracciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jScrollPane1.setViewportView(jTextAreaInteracciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabelInteracciones, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelInteracciones, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelInteracciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInteracciones;
    // End of variables declaration//GEN-END:variables
}
